<?php

$_COS_LANG_MODULE['Enter title'] = 'Indtast titel';
$_COS_LANG_MODULE['Enter content'] = 'Indtast indhold';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Ikke en korrekt beregning af captcha';
$_COS_LANG_MODULE['Fill out the contact form'] = 'Udfyld kontaktformularen';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Email'] = 'E-mail';
$_COS_LANG_MODULE['Enter your message'] = 'Indtast din besked';
$_COS_LANG_MODULE['Submit'] = 'Indsend';
