<?php


// Translation of file /modules/contact/module.php

$_COS_LANG_MODULE['Enter title'] = 'Enter title';
$_COS_LANG_MODULE['Enter content'] = 'Enter content';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Not a correct calculation of captcha';

// Translation of file /modules/contact/views.php

$_COS_LANG_MODULE['Fill out the contact form'] = 'Fill out the contact form';
$_COS_LANG_MODULE['Title'] = 'Title';
$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Enter your message'] = 'Enter your message';
$_COS_LANG_MODULE['Submit'] = 'Submit';
