<?php

$_COS_LANG_MODULE['Enter title'] = 'Skriv inn tittel';
$_COS_LANG_MODULE['Enter content'] = 'Tast innhold';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Ikke en korrekt beregning av captcha';
$_COS_LANG_MODULE['Fill out the contact form'] = 'Fyll ut kontaktskjema';
$_COS_LANG_MODULE['Title'] = 'Tittel';
$_COS_LANG_MODULE['Email'] = 'E-post';
$_COS_LANG_MODULE['Enter your message'] = 'Skriv inn din melding';
$_COS_LANG_MODULE['Submit'] = 'Send inn';
