<?php

$_COS_LANG_MODULE['Enter title'] = 'Titel eingeben';
$_COS_LANG_MODULE['Enter content'] = 'Geben Sie Inhalt';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Nicht eine korrekte Berechnung der Captcha';
$_COS_LANG_MODULE['Fill out the contact form'] = 'Füllen Sie das Kontaktformular';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Email'] = 'E-Mail';
$_COS_LANG_MODULE['Enter your message'] = 'Geben Sie Ihre Nachricht';
$_COS_LANG_MODULE['Submit'] = 'Einreichen';
