<?php

$_COS_LANG_MODULE['Enter title'] = 'Kirjoita otsikko';
$_COS_LANG_MODULE['Enter content'] = 'Anna sisällön';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Ei laskea oikein captcha';
$_COS_LANG_MODULE['Fill out the contact form'] = 'Täytä yhteydenottolomake';
$_COS_LANG_MODULE['Title'] = 'Otsikko';
$_COS_LANG_MODULE['Email'] = 'Sähköposti';
$_COS_LANG_MODULE['Enter your message'] = 'Kirjoita viestisi';
$_COS_LANG_MODULE['Submit'] = 'Esittää';
