<?php

$_COS_LANG_MODULE['Enter title'] = 'Ange titel';
$_COS_LANG_MODULE['Enter content'] = 'Ange innehåll';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Inte en korrekt beräkning av captcha';
$_COS_LANG_MODULE['Fill out the contact form'] = 'Fyll i kontaktformuläret';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Email'] = 'E';
$_COS_LANG_MODULE['Enter your message'] = 'Skriv in ditt meddelande';
$_COS_LANG_MODULE['Submit'] = 'Skicka in';
